import os

## DIR PATH
ROOT_DIR_PATH = os.path.abspath(os.path.dirname(__file__))
LOG_DIR_PATH = os.path.join(ROOT_DIR_PATH, 'log')
SENSOR_DIR_PATH = os.path.join(ROOT_DIR_PATH, 'sensor')

## DISPLAY CONFIG
DISPLAY_ON = False

## DRIVE CONFIG
MOTOR_STOP_PIN_NUM = 15

SERVO_PIN_NUM = 0
MOTOR_PIN_NUM = 15
COMMU_PIN_NUM = 20

SERVO_LEFT = 270    #40
SERVO_MID = 370     #90
SERVO_RIGHT = 470   #140
## 가공 전 Steering Value
__SERVO_LEFT = 40#38 #35
__SERVO_MID = 90 # #65
__SERVO_RIGHT = 140#97 #100

MOTOR_STOP = 380
MOTOR_FORWARD = 392
FIRST_FORWARD = True
FIRST_MOTOR_FORWARD = 405


## SERVER CONFIG
SERVER_IP_ADDR = '127.0.0.1'
SERVER_PORT = 4000